# Generated by Django 4.2 on 2023-05-16 00:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.DateTimeField(default=django.utils.timezone.now)),
                ('campoDaEscolha', models.CharField(max_length=200, verbose_name='texto de escolha')),
                ('votos', models.IntegerField(default=0, verbose_name='votos')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textoDaPergunta', models.CharField(max_length=200)),
                ('dataDePublicacao', models.DateTimeField(verbose_name='data de publicação')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
