# Generated by Django 4.2 on 2023-05-16 00:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_escolha_pergunta_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='escolha',
            name='criadoEm',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='escolha',
            name='pergunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.pergunta'),
        ),
    ]
